[package]
name = "test-action"
version = "0.2.0"
authors = ["topecongiro <seuchida@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "test-action-v2"
path = "src/action.rs"

[dependencies]
